name: FarmManager
main: ru.ruscalworld.farmmanager.FarmManager
author: RuscalWorld
api-version: '1.16'
version: ${version}
commands:
    farmmanager:
        aliases: [fm,farm]
        description: Main command of FarmManager
        permission: farmmanager.command
    spawnrate:
        description: Shows current mob spawn parameters